# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 02:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_com', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('subject', models.CharField(max_length=60)),
                ('notes', models.TextField()),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'Meeting'), (2, 'Email'), (3, 'Phone')])),
                ('date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'communications',
                'ordering': ['date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='communication',
            unique_together=set([('date', 'owner')]),
        ),
    ]
