# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 14:54
from __future__ import unicode_literals

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_contents_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contents',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='contents',
            name='order',
            field=courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
