# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
