# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestampmodel',
            old_name='mofified',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
    ]
