# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160606_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-timestamp', 'modified']},
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
